# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('dish_type', models.CharField(choices=[('Appitizer', 'Appitizer'), ('Main course', 'Main course'), ('Dessert', 'Dessert')], max_length=200, verbose_name='Dish type')),
                ('dish', models.CharField(max_length=200, verbose_name='Dish Name')),
                ('common_allergy_ingredients', models.CharField(blank=True, max_length=200, null=True, verbose_name='common food allergy ingredients')),
                ('crockpot', models.BooleanField(verbose_name='will this dish come in a container that will need an outlet?')),
            ],
        ),
    ]
