# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0003_auto_20171107_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='common_allergy_ingredients',
        ),
        migrations.RemoveField(
            model_name='items',
            name='crockpot',
        ),
        migrations.RemoveField(
            model_name='items',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='items',
            name='dish_type',
        ),
        migrations.AddField(
            model_name='items',
            name='tshirt_size',
            field=models.CharField(default='medium', max_length=200, verbose_name='T-shirt size'),
        ),
        migrations.AddField(
            model_name='items',
            name='tutorial_session',
            field=models.CharField(choices=[('Webinar: Friday April 20th 11:00-11:45', 'Session_1'), ('Webinar: Thursday April 19th 11:00-11:45', 'Session_2'), ('These times do not work for me, but i still would like an introduction', 'times_do_not_work'), ('I feel comfortable with scrach and do not need to attend a tutorial session', 'none')], default='Session_1', max_length=20, verbose_name='Scratch Tutorial Session'),
        ),
    ]
