# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0004_auto_20180405_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='tshirt_size',
        ),
        migrations.RemoveField(
            model_name='items',
            name='tutorial_session',
        ),
        migrations.AddField(
            model_name='items',
            name='common_allergy_ingredients',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What is in your dish that others might be allergic to?'),
        ),
        migrations.AddField(
            model_name='items',
            name='crockpot',
            field=models.BooleanField(default=False, verbose_name='will this dish come in a container that will need an outlet?'),
        ),
        migrations.AddField(
            model_name='items',
            name='dish',
            field=models.CharField(default=' ', max_length=200, verbose_name='Dish Name'),
        ),
        migrations.AddField(
            model_name='items',
            name='dish_type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main_course', 'Main course'), ('Dessert', 'Dessert')], default='Main_Course', max_length=20, verbose_name='Dish type'),
        ),
    ]
